### ISSUE TITLE
Code_graph feature request

### ISSUE THREAD

**Issue by javimarlop** [ropensci/Rclean#206]
Is there a way to obtain a graph with just the relationships between the objects? I mean ignoring nodes showing line numbers in which no new objects are created. Thanks!

**Comment by MKLau** [comment]
Hi @javimarlop, I think you could do that by:

- run the code through `clean()` with all of the objects as inputs to the var argument
- save there cleaned code with keep to a new script
- run `code_graph()` on that new script. 

That would result in a plot that only shows code that produces objects.

**Comment by MKLau** [comment]
Let me know if I got what you’re asking for.

**Comment by javimarlop** [comment]
That procedure still shows code lines in which no new objects are produced. The idea is to apply the code_graph function to visualize the design of any system dynamic model previously coded, not really for provenance or reproducibility purposes. I can try to prune the igraph or graphNEL object created within the function to only show relationships between objects. Does this make sense to you? Thanks for the feedback!

**Comment by MKLau** [comment]
Ah, I missed that you wanted relationships among objects only. That won't be possible using `code_graph()` as it's currently written. You could fork Rclean and alter it as you need to, but it's probably better to just go look at [CodeDepends](http://www.omegahat.net/CodeDepends/). It has a number of tools for doing static investigations of code, and I have a recollection that they have a graph visualization that does what you're after. 

Let me know if you have more questions, but for now I'll mark this issue as closed.

**Comment by javimarlop** [comment]
Thanks! In deed, `makeVariableGraph` does the trick!

**Comment by MKLau** [comment]
Great, glad you found that! Happy to help.
