### ISSUE TITLE
Multiple statements on a line

### ISSUE THREAD

**Issue by blernermhc** [ropensci/Rclean#78]
Rclean uses line numbers but does not use the column information in the JSON when extracting source code.  As a result, if there are multiple statements on a single line, they will all be included in the minimized script even if they do not all contribute to the desired output.  For example,
```
a <-1 ; b <- 2
```
Rclean with a target of "a" or "b" will include both statements.

**Comment by MKLau** [comment]
This will be addressed by #163.
